### ISSUE TITLE
refactor: can lite_ref be an optional dependency?

### ISSUE THREAD

**Issue by calebkiage** [jinyus/dart_beacon#116]
**Description**

I just discovered this package and it seems really useful from my preliminary tests. One thing I've noticed is that state_beacon bundles lite_ref when installed. Can the parts using lite_ref be moved to a separate package so that people who don't need the dependency injection can still use it without pulling in lite_ref?

**Requirements**

- [ ] There is no drop in test coverage.

**Comment by jinyus** [comment]
I just published the stable release. You can now use [state_beacon_flutter](https://pub.dev/packages/state_beacon_flutter) if you don't want to pull lite_ref
