### ISSUE TITLE
derivedStream?

### ISSUE THREAD

**Issue by lukepighetti** [jinyus/dart_beacon#58]
Common pattern in state management to depend on a reactive value and use it to manage/switch streams

ie: 

```dart
final userProfileSignal = derivedStreamSignal<UserProfile>((){
  final uid = myUidSignal();
  return myUserProfileStream(uid);
});
```

and then have it automatically handle setup and teardown of the profile stream as the user id changes

Is does state_beacon have this feature, and if not, please consider this a feature request

**Comment by jinyus** [comment]
That's an interesting concept, I think the current derived beacon could be modified to treat streams differently..

**Comment by jinyus** [comment]
Added in v0.33.2
