### ISSUE TITLE
Beacon behavior discussion

### ISSUE THREAD

**Issue by s0nerik** [jinyus/dart_beacon#7]
I didn't test that yet, but looking at the code (trying to figure out why `Beacon` is twice as fast as `context_watch` 😅) it seems like Beacon observers created via `watch(context)`:
- mark context for build even if conditional `watch()` call is gone from `build` while context is still `mounted`.

  Example:
  ```
  Widget build(BuildContext context) {
    beacon1.watch(context);
    if (condition) {
      beacon2.watch(context);
    }
  }
  ```
  I suspect that in this case, if `condition` was initially `true` but later became `false`, the widget will still get rebuilt on `beacon2` notification, even though it's not desirable. For background: the same behavior is [observed with any `InheritedWidget`](https://github.com/flutter/flutter/issues/106549) right now, so that's in line with Flutter in some way. :) On the other hand, [`context_watch` handles that case, trading it for a bit of performance](https://github.com/s0nerik/context_watch/blob/f3b0d5339c79d4ec98ea42a6f4ac4cb724b850d3/packages/context_watch_base/lib/src/inherited_context_watch.dart#L157)
- are never removed until the `Beacon` itself is destroyed. I imagine this _might_ cause some problems in an extreme case of `Beacon` being defined globally and having many listeners that start/stop listening to it frequently. `context_watch` removes them upon both ["gone from build"](https://github.com/s0nerik/context_watch/blob/f3b0d5339c79d4ec98ea42a6f4ac4cb724b850d3/packages/context_watch_base/lib/src/inherited_context_watch.dart#L158C8-L158C8) and ["widget unmounted"](https://github.com/s0nerik/context_watch/blob/f3b0d5339c79d4ec98ea42a6f4ac4cb724b850d3/packages/context_watch_base/lib/src/inherited_context_watch.dart#L130) events.

I'm not 100% confident in either of these statements as I haven't tested `Beacon` yet, but these are what seem to be the major behavior differences between `Beacon` and `context_watch` and the actual reasons why `Beacon`s `watch()` is faster than `context_watch`s by a bigger margin compared to other observables/observing_mechanisms.

To me, it feels natural and "right" to fully unsubscribe the context from observable changes when the context is no longer interested in them (thus, they're no longer referenced from `build` method). And even more so when the context is destroyed. That being said, I still haven't fully decided if these two cases are worth caring about that much, I'd like to know what you think about it.

**Comment by jinyus** [comment]
Regarding your first point, I decided to copy the behavior of riverpod/inherited widget. It could be achieved with a `Watch` widget similar to the one in signals, but that widget has some hidden footguns, where it watches all signals in its subtree:

```
Watch
  |_Container
      |_ Column
          |_ Text  <- signal watched here will rebuild the entire Container and Column
```  

About point 2. It does unsubscribe when the widget is unmounted/context is garbage collected using the finalizer or if the value is ever modified (whichever happens first)

**Comment by s0nerik** [comment]
Thanks for your answers.

> Regarding your first point, I decided to copy the behavior of riverpod/inherited widget.

Gotcha. Looks like most observability solutions choose slightly better overall performance over the potential extra rebuilds reduction. I'll re-evaluate whether it is worth it to handle that case.

> About point 2. It does unsubscribe when the widget is unmounted/context is garbage collected using the finalizer or if the value is ever modified (whichever happens first)

I see, my initial impression was that `_finalizer` will only trigger the callback when the Beacon itself is GC'd, while in reality it can be attached to anything (and is actually attached to all listening contexts). Thanks for the clarification.

Now I'm curious if there can be any major time gap between the context's `unmount` and a `Finalizer`s callback for that context. I'm not an expert on weak references in Dart, but I expect that the callback is called after a GC pass that can be delayed an arbitrary amount of time, potentially triggering the `unsub` later than "right after unmount". Do you consider this assessment to be correct?

**Comment by jinyus** [comment]
> but I expect that the callback is called after a GC pass that can be delayed an arbitrary amount of time, potentially triggering the `unsub` later than "right after unmount". Do you consider this assessment to be correct?

That's correct. I did have a custom widget that handled unsub right after unmount, but after testing finalizer, it seems to run right after the widget is unmounted, so I decided that's good enough.
